<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="BAJAComponente.aspx.cs" Inherits="TPLAB3_GRUPO4.Usuarios.Admisnistrador.BAJAComponente" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta charset="utf-8" />
    <title>Baja de Componente</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server" class="container mt-5">
        <h2 class="mb-4 text-danger">Baja de Componente</h2>

        <!-- Ingreso de ID -->
        <div class="mb-3">
            <label for="txtbuscar" class="form-label">Ingresar ID del Componente</label>
            <asp:TextBox ID="txtbuscar" runat="server" CssClass="form-control" />
        </div>

        <!-- Botón para Buscar -->
        <div class="mb-3">
            <asp:Button ID="btnBuscar" runat="server" Text="Buscar" CssClass="btn btn-danger" OnClick="btnBuscar_Click" />
        </div>

        <!-- GridView de Componentes -->
        <div class="mb-4">
            <asp:GridView ID="grdComp" runat="server"
                AutoGenerateColumns="False"
                AutoGenerateDeleteButton="True"
                CssClass="table table-bordered table-striped table-hover"
                OnRowDeleting="grdComponentes_RowDeleting"
                CellPadding="4"
                ForeColor="#333333"
                GridLines="None">

                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:TemplateField HeaderText="ID Componente">
                        <ItemTemplate>
                            <asp:Label ID="lblID" runat="server" Text='<%# Eval("IDComponente") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="Nombre">
                        <ItemTemplate>
                            <asp:Label ID="lblNombre" runat="server" Text='<%# Eval("Nombre") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>
        </div>

        <!-- Mensaje de resultado -->
        <asp:Label ID="lblMensaje" runat="server" CssClass="form-text fw-bold"></asp:Label>
    </form>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
