<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="BajaEmpleado.aspx.cs" Inherits="TPLAB3_GRUPO4.Usuarios.Admisnistrador.BajaEmpleado" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta charset="utf-8" />
    <title>Baja de Empleado</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server" class="container mt-5">
        <h2 class="mb-4 text-danger">Baja de Empleado</h2>
        <asp:Button ID="btnVolver" runat="server" OnClick="btnVolver_Click" Text="Volver" CssClass="btn btn-secondary" />

        <!-- ID Usuario -->
        <div class="mb-3">
            <label for="txtIDUsuario" class="form-label">Ingresar ID Usuario</label>
            <asp:TextBox ID="txtIDUsuario" runat="server" CssClass="form-control" />
        </div>

        <!-- GridView de empleados -->
        <div class="mb-4">
            <asp:GridView ID="grdBajaUsuario" runat="server"
                AutoGenerateColumns="False"
                AutoGenerateDeleteButton="True"
                CssClass="table table-bordered table-striped table-hover"
                OnRowDeleting="grdbajaUsuario_RowDeleting"
                CellPadding="4"
                ForeColor="#333333"
                GridLines="None">

                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:TemplateField HeaderText="ID Usuario">
                        <ItemTemplate>
                            <asp:Label ID="lblID" runat="server" Text='<%# Eval("IDUsuarios") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="Nombre">
                        <ItemTemplate>
                            <asp:Label ID="lblNombre" runat="server" Text='<%# Eval("Nombre") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>
        </div>

        <!-- Botón para eliminar -->
        <div class="mb-3">
            <asp:Button ID="btnEliminarEmpleado" runat="server" Text="Eliminar Empleado" CssClass="btn btn-danger" OnClick="btnEliminarEmpleado_Click" />
        </div>

        <!-- Mensaje -->
        <div>
            <asp:Label ID="lblMensaje" runat="server" CssClass="form-text fw-bold"></asp:Label>
        </div>
    </form>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
